package Defaults

import (
	"GServer/TaskManager"
)

const (
	DEFAULT_HTTP_SERVER_HOST_ADDRESS = "localhost:3050"

	YTS_API_BASE_URL                  = "https://yts.mx/api/v2"
	YTS_API_LIST_MOVIES_ENDPOINT      = "/list_movies.json"
	YTS_API_MOVIE_DETAILS_ENDPOINT    = "/movie_details.json"
	YTS_API_MOVE_SUGGESTIONS_ENDPOINT = "/movie_suggestions.json"

	INTERNET_ARCHIVE_BASE_URL                 = "https://archive.org"
	INTERNET_ARCHIVE_ADVANCED_SEARCH_ENDPOINT = "/advancedsearch.php"
	INTERNET_ARCHIVE_TORRENT_URL_FORMAT       = INTERNET_ARCHIVE_BASE_URL + "/download/%s/%s_archive.torrent"

	CRAWLER_YTS_MOVIE_COUNT_PER_SEARCH              = 30
	CRAWLER_INTERNET_ARCHIVE_MOVIE_COUNT_PER_SAERCH = 30

	TASKS_MAX_THREADS_HTTP_SERVER = TaskManager.UNLIMITED_THREAD_COUNT

	TASKS_MAX_THREADS_CRAWLER_MAIN = TaskManager.UNLIMITED_THREAD_COUNT

	TASKS_MAX_THREADS_MOVIE_CRAWLER_YTS = 20
	TASKS_MAX_THREADS_MOVIE_CRAWLER_IA  = 20

	TASKS_MAX_THREADS_YTS_MOVIE_PARSER = 10
	TASKS_MAX_THREADS_IA_MOVIE_PARSER  = 10

	TASKS_MAX_THREADS_YTS_TORRENT_PARSER = 10
	TASKS_MAX_THREADS_IA_TORRENT_PARSER  = 10

	TASKS_EXECUTION_DELAY_HTTP_SERVER = TaskManager.DISABLED_TASK_DELAY

	TASKS_EXECUTION_DELAY_CRAWLER_MAIN = TaskManager.DISABLED_TASK_DELAY

	TASKS_EXECUTION_DELAY_MOVIE_CRAWLER_YTS = TaskManager.DISABLED_TASK_DELAY
	TASKS_EXECUTION_DELAY_MOVIE_CRAWLER_IA  = TaskManager.DISABLED_TASK_DELAY

	TASKS_EXECUTION_DELAY_YTS_MOVIE_PARSER = TaskManager.DISABLED_TASK_DELAY
	TASKS_EXECUTION_DELAY_IA_MOVIE_PARSER  = TaskManager.DISABLED_TASK_DELAY

	TASKS_EXECUTION_DELAY_YTS_TORRENT_PARSER = TaskManager.DISABLED_TASK_DELAY
	TASKS_EXECUTION_DELAY_IA_TORRENT_PARSER  = TaskManager.DISABLED_TASK_DELAY
)
